install:
	install -m600 ./dot-offlineimaprc ~/.offlineimaprc
	install -m600 ./dot-offlineimap.py ~/.offlineimap.py
	install -m600 ./dot-msmtprc ~/.msmtprc
	install -m600 ./net.thoughtspot.email.plist ~/Library/LaunchAgents/net.thoughtspot.email.plist
